name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: [1.12, 1.13, 1.14]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.version}}

      - run: go get -v -d ./...
      - run: go build -v ./...
